# Generated by Django 4.2.7 on 2023-12-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Телеграм ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('seals', models.BigIntegerField(blank=True, null=True, verbose_name='Количество печатей')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserDayJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('numerology_count', models.IntegerField(verbose_name='Раздел нумерологии')),
                ('core_synthesis', models.IntegerField(verbose_name='Синтез ядра')),
                ('forecat', models.IntegerField(verbose_name='Прогноз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_numbers.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал посещений раздел',
                'verbose_name_plural': 'Журналы посещений раздел',
            },
        ),
        migrations.CreateModel(
            name='UserBaseNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_path_number', models.IntegerField(blank=True, null=True, verbose_name='Число жизненного пути')),
                ('birthday_number', models.IntegerField(blank=True, null=True, verbose_name='Число дня рождения')),
                ('expression_number', models.IntegerField(blank=True, null=True, verbose_name='Число экспрессии')),
                ('spirit_awake_number', models.IntegerField(blank=True, null=True, verbose_name='Число духовного пробуждения')),
                ('personality_number', models.IntegerField(blank=True, null=True, verbose_name='Число личности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_numbers.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Базовое число',
                'verbose_name_plural': 'Базовые числа',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('action', models.TextField(verbose_name='Действие')),
                ('money', models.IntegerField(verbose_name='Количество рублей')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_numbers.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Время и Дата')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('answer_pics', models.ManyToManyField(blank=True, to='magic_numbers.answerpic', verbose_name='Картинки ответа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_numbers.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.AddField(
            model_name='answerpic',
            name='pic_consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_numbers.consultation', verbose_name='Консультация'),
        ),
    ]
