# Generated by Django 4.2.7 on 2023-12-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_numbers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdayjournal',
            old_name='forecat',
            new_name='forecast',
        ),
    ]
